In [1]:
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
end_date = datetime.now()
start_date = end_date - timedelta(days=365)

# Pobranie danych o cenie akcji Microsoftu
msft = yf.Ticker("MSFT")
msft_data = msft.history(start=start_date.strftime('%Y-%m-%d'), end=end_date.strftime('%Y-%m-%d'))[['Open', 'Close']]

In [35]:
ticker = 'MSFT'
start_time = '2020-01-01'
end_time = '2021-01-01'
ticker_data = yf.Ticker(ticker)

ticker_data.history(period = '1d', interval='3h')

MSFT: Invalid input - interval=3h is not supported. Valid intervals: [1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo]

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [175]:
from datetime import datetime
import pandas as pd

start_time = datetime.strptime('2024-09-03 09:00:00', '%Y-%m-%d %H:%M:%S')
end_time = datetime.strptime('2024-10-03 09:00:00', '%Y-%m-%d %H:%M:%S')
start_date_str = start_time.date().strftime('%Y-%m-%d')
end_date_str = end_time.date().strftime('%Y-%m-%d')

ticker_df = yf.Ticker(ticker).history(
        start=start_time, end=end_time, interval= "1d")[['Close']]
ticker_df.index = ticker_df.index.tz_localize(None).date # Delete timezone info and hours





full_data_range = pd.date_range(
        start= start_date_str, end=end_date_str)
ticker_df = ticker_df.reindex(full_data_range)

# If is work day
if end_time.weekday() < 5:
    # If last cell is NaN
    if pd.isna(ticker_df['Close'].iloc[-1]):
        ticker_df.loc[ticker_df.index[-1], 'Close'] = yf.Ticker(ticker).info['currentPrice']

ticker_df['Close'] = ticker_df['Close'].ffill()
if ticker_df['Close'].isna().any():
    ticker_df['Close'] = ticker_df['Close'].bfill()

ticker_df

                 Close
2024-09-03  409.440002
2024-09-04  408.899994
2024-09-05  408.390015
2024-09-06  401.700012
2024-09-07  401.700012
2024-09-08  401.700012
2024-09-09  405.720001
2024-09-10  414.200012
2024-09-11  423.040009
2024-09-12  427.000000
2024-09-13  430.589996
2024-09-14  430.589996
2024-09-15  430.589996
2024-09-16  431.339996
2024-09-17  435.149994
2024-09-18  430.809998
2024-09-19  438.690002
2024-09-20  435.269989
2024-09-21  435.269989
2024-09-22  435.269989
2024-09-23  433.510010
2024-09-24  429.170013
2024-09-25  432.109985
2024-09-26  431.309998
2024-09-27  428.019989
2024-09-28  428.019989
2024-09-29  428.019989
2024-09-30  430.299988
2024-10-01  420.690002
2024-10-02  417.130005
2024-10-03  417.130000

In [170]:
yf.Ticker(ticker).info['currentPrice']

417.13